name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:     
      
      - run: docker build . --file Dockerfile --tag ghacupha/fast-api-uvicorn:0.0.1-SNAPSHOT

      - run: docker login --username=$DOCKERHUB_USERNAME --password=$DOCKERHUB_TOKEN

      - run: docker push ghacupha/fast-api-uvicorn:0.0.1-SNAPSHOT
