name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - 
      name: Build the Docker image
      uses: docker/build-push-action@v2
      run: docker build . --file Dockerfile --tag ghacupha/fast-api-uvicorn:0.0.1-SNAPSHOT

    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - 
      name: Push the Docker image
      uses: docker/build-push-action@v2
      run: docker push ghacupha/fast-api-uvicorn:0.0.1-SNAPSHOT
